### ISSUE TITLE
Would it be possible for you to add some debug logging?

### ISSUE THREAD

**Issue by stodge** [faceless2/zeroconf#11]
Would it be possible for you to add some debug logging? I have a weird situation where SRV(TTL=0) and TXT(TTL=0) packets are broadcast from an external service, but Zeroconf doesn't seem to respond to them. Or at least, the ZeroconfListener.serviceExpired() isn't invoked. When this happens, Zeroconf will eventually expire the service after the correct interval according to the TTL and when the mDNS record was last modified. It isn't consistent; sometimes Zeroconf expires the service, sometimes it doesn't.

I'm not pointing the finger at Zeroconf; there's a chance that the external system that hosts the service in question is doing weird things, or that my software is somehow blocking the Zeroconf thread (not too likely?) but I'm trying to debug the problem at the moment.

I'd add some debug statements to Zeroconf myself, but I figured you'd know the best places to add them for maximum effect.

Thanks again.

Edit: my plan is to locally add some logging tomorrow.

**Comment by faceless2** [comment]
If you take a look at src/test/com/bfo/zeroconf/Test.java you'll see how to do this - add a Listener, log everything!

From your description it... should be working. My first thought is I wonder if the expiry is being queued then replaced by a later packet? I've added some logging code, the diff should be fairly obvious (if you're fighting java logging system, as I usually am, just force DEBUG to true and change `debug(String msg)` to just System.out.println(msg).

I suppose what I'd be looking for is what happens when those TTL=0 messages arrive. The will queue an expiry task - is that task then replaced shortly afterwards? If it is then your listened will have logged the packets, post them and we'll have a look.

**Comment by stodge** [comment]
Thanks again. I'll run your latest changes and see if I can spot anything obvious. I'll try to debug down into the code, but at the moment, the problem isn't consistently reproducible on demand.

Unfortunately, I doubt I'll be able to post the packets. I'll ask, but I think it's very unlikely. Sorry. ☹️

**Comment by faceless2** [comment]
Oh that's fine. I don't really want to debug them :-)

**Comment by stodge** [comment]
Unfortunately I've been fighting other fires that obscured this particular problem. The only thing I can surmise at the moment is that one mDNS message contains multiple mDNS records, so the scenario seems to be:

14:30:00 TXT SERVICE1 TTL=0
14:30:00 TXT SERVICE2 TTL=120

My theory is that Zeroconf may be missing the cancellation of SERVICE1. SERVICE2 is successfully discovered. This is only a theory based on what little evidence I can see, and at this point I still don't want to point fingers at Zeroconf. There's still a chance the external system is to blame.

**Comment by stodge** [comment]
Am I right in thinking that ZeroconfListener.serviceModified() is called when the TXT record is received with TTL=0? If so, is there a way to check the TTL in this callback?

I noticed that ZeroconfListener.serviceModified() was called after ZeroconfListener.serviceExpired(). Though the ordering of the answers in the mDNS message was SRV(TTL=0) and then TXT(TTL=0). So that makes sense. For some reason, I expected the ordering to be reversed. mDNS is rather odd to my untrained, uneducated eye....

**Comment by faceless2** [comment]
Yes. The general idea is there is a Service (an SVC) with various associated records - A, AAAA, TXT, all of which can have different expiration dates. When a record is processed an event is queued at the TTL time to expire that data (which, in the case of TXT records, simply calls `service.setText(null)`. After the record is processed, if the service was changed then `serviceModifed()` is called as a general "something changed" notification.

But I wouldn't too much store in the relative order of these events, it's not specified in the API and it definitely not guaranteed to correlate to the order of the records - a few things had to be reordered to make sure records existed before the were modified, etc. And of course, the server can send TTL=0 events in different packets and being UDP, relative packet order is unpredictable anyway.

**Comment by stodge** [comment]
I just realised I'm receiving multiple SRV and TXT records for the same service. Is this normal for mDNS in your experience?

2025-01-17 08:15:49.256455	SRV	Service: SERVICE1, TTL: 120
2025-01-17 08:15:49.256455	TXT	Service: SERVICE1, TTL: 120, VALID TEXT PROPERTIES
2025-01-17 08:15:57.539092	SRV	Service: SERVICE1, TTL: 0
2025-01-17 08:15:57.539092	TXT	Service: SERVICE1, TTL: 0, NO TEXT PROPERTIES
2025-01-17 08:15:57.539603	SRV	Service: SERVICE1, TTL: 0
2025-01-17 08:15:57.539603	TXT	Service: SERVICE1, TTL: 0, NO TEXT PROPERTIES
2025-01-17 08:15:57.540097	SRV	Service: SERVICE1, TTL: 0
2025-01-17 08:15:57.540097	TXT	Service: SERVICE1, TTL: 0, NO TEXT PROPERTIES
...

Zeroconf invokes these callbacks:

- serviceModified(service)
- serviceExpired(service)
- serviceModified(service)
- serviceModified(service)
- serviceModified(service)
- ...

I think I can safely ignore any updates without text properties for an unknown service. But does this make sense or is the external service doing weird things?

Thanks

PS - Sorry, this comment should be a conversation, but those aren't enabled on this repo.

**Comment by faceless2** [comment]
Those TTL=0 records are signalling the expiration of the service - that's what TTL=0 is for.

I wouldn't presume to say what's "normal", but certainly if it's got a TTL=0 then it's telling you something is no longer there, so safe to ignore.

**Comment by stodge** [comment]
Thanks. I was just wondering if it was abnormal for to receive the record with TTL=0 over and over again. I always assumed I'd receive it just once.
