### ISSUE TITLE
Exception in thread "Thread-0" java.lang.Error

### ISSUE THREAD

**Issue by stodge** [faceless2/zeroconf#2]
I'm trying to listen for services using:

`jRegistry.query("_TEST._udp.local.", null);`

But I'm getting this exception, which I assume means the library doesn't like the fact the service type ends with a full stop?

> Exception in thread "Thread-0" java.lang.Error: "_TEST._udp.local." "_TEST._udp.local"
> 	at com.bfo.zeroconf.Record.writeName(Record.java:300)
> 	at com.bfo.zeroconf.Record.write(Record.java:223)
> 	at com.bfo.zeroconf.Packet.write(Packet.java:278)
> 	at com.bfo.zeroconf.Zeroconf$ListenerThread.run(Zeroconf.java:653)

**Comment by faceless2** [comment]
Whoops, throwing an Error is very bad manners. Sorry about that, we'll get those fixed.

Correct: it should be `zc.query("_TEST._udp.local", null)` or `zc.query("_TEST._udp", null)`

**Comment by faceless2** [comment]
Fixed in trunk

**Comment by stodge** [comment]
Thanks!
