### ISSUE TITLE
Any way to override the TTL when announcing a service?

### ISSUE THREAD

**Issue by stodge** [faceless2/zeroconf#7]
Is there a way to override the TTL when announcing a service? We need to stipulate a TTL of 2 minutes for any services that get announced in our emulator. It looks like the TTL is hard coded for each type of record, e.g.:

`return new Record(TYPE_TXT, CLAZZ, 4500, name, map);`

Looking at the mDNS packets we get from the external system, all mDNS record types it publishes have a TTL of 2 minutes. We have an in-house emulator we use for testing.

Thanks again.

**Comment by stodge** [comment]
I'm working through the code to see if I can offer a patch. Not sure of the best solution yet, as I don't want to break your design decisions. 😃 

For example, I could change Record.java to use system properties, but I'm not sure I like that idea:
```Java
        final int ttl = Record.getTimeToLive("zeroconf.ttl.ptr", DEFAULT_PTR_TTL);
        return new Record(TYPE_PTR, CLAZZ, ttl, name, value);
```

App code would include:

```java
        System.setProperty("zeroconf.ttl.ptr", "120");
```

**Comment by stodge** [comment]
I don't love this idea - it's a lot of work every time the TTL is needed. It means my app code is clean though.

Another option is this:

```java
    static final int SRV_TTL = Record.getTimeToLive(SRV_TTL_PROPERTY_NAME, DEFAULT_SRV_TTL);
```

And the app code:

```java
return new Record(TYPE_SRV, CLAZZ, SRV_TTL, name, new SrvData(priority, weight, port, host));
```

This means I need to define 5 system properties on the command line, which I don't love but it's not a deal breaker. I haven't tested these changes.

**Comment by stodge** [comment]
Saving ideas while I work this through in my head. Another option, but I'm not sure I like it. Create a new class:

```java
public class Config {

    static final int DEFAULT_SRV_TTL = 120;
    static final int DEFAULT_PTR_TTL = 28800;
    static final int DEFAULT_TXT_TTL = 4500;
    static final int DEFAULT_A_TTL = 120;
    static final int DEFAULT_AAAA_TTL = 120;

    public static int SRV_TTL = DEFAULT_SRV_TTL;
    public static int PTR_TTL = DEFAULT_PTR_TTL;
    public static int TXT_TTL = DEFAULT_TXT_TTL;
    public static int A_TTL = DEFAULT_A_TTL;
    public static int AAAA_TTL = DEFAULT_AAAA_TTL;
}
```

Change Record.java accordingly:

```java
return new Record(TYPE_TXT, CLAZZ, Config.TXT_TTL, name, map);
```

The application would configure the TTLs:

```java
        // Setup Zeroconf TTLs.
        Config.AAAA_TTL = 120;
        Config.A_TTL = 120;
        Config.SRV_TTL = 120;
        Config.PTR_TTL = 120;
        Config.TXT_TTL = 120;
```

**Comment by stodge** [comment]
Bah, none of these work properly. The services expire every 2 minutes.

The mDNS packet timings according to Wireshark were:

08:39:53.930295 Standard query response - service announced
08:41:57.640174 Standard query response - service expired

**Comment by stodge** [comment]
Strange I get the same problem with an un-modified copy from master, using Zeroconf's default TTLs for each record type. The service always expires after 120s:

```
2024-07-18 09:23:51.034235	Service: SERVICE1, RESOLVED (subscriber)
2024-07-18 09:25:51.000610	Service: SERVICE1, RE-ANNOUNCE (publisher)
2024-07-18 09:25:51.000611	Service: SERVICE1, TTL=108 (publisher)
2024-07-18 09:25:51.610932	Service: SERVICE1, MODIFIED (subscriber)
2024-07-18 09:25:51.613946	Service: SERVICE1, EXPIRED (subscriber)
2024-07-18 09:25:51.613946	Service: SERVICE1, DELETED (subscriber)
```

**Comment by faceless2** [comment]
Sorry - distracted with work and hardware failures over last few days. While I'm not sure how useful it will be to set the TTL, I appreciate it's technically something we can do but don't, and it's easy enough to add.

Currently address records are 120s and service/pointer required longer - whatever value I took was lifted from what I was seeing as fairly standard on my network here (a mix of Apple and Linux). If you're happy with that level of granularity I would probably go with:

* adding `setTTL(int ms)` and `setAddressTTL(int ms)` methods to `Service.Builder`, and store these values on the Service in a package-private way.
* `Packet(Service)`, take those values and set them on each Record we create by calling `record.setTTL()`

Happy with that model? It's about 5mins work, I can add easily enough

EDIT: I've presumed that TXT, SRV, PTR records would all have the same TTL, but I suppose it makes sense to add TTL levels for each and it's no extra work

**Comment by stodge** [comment]
Should line 1010 of Zeroconf.java be this?

```java
expire(service, ttl, new Runnable() {
```

**Comment by faceless2** [comment]
Yes, yes it should :-) I'm trying to reannounce at 90% of the TTL. Good catch!

EDIT: just pushed that to HEAD

**Comment by faceless2** [comment]
OK, easy fix. Just pushed to HEAD, so now you can do this:
```java
Service.Builder builder = new Service.Builder(...);
int ttl = 120; // time in seconds
builder.setTTL_PTR(ttl);
builder.setTTL_SRV(ttl);
builder.setTTL_TXT(ttl);
builder.setTTL_A(ttl);
Service service = builder.build();
service.announce();
```
Working here, so I'll close this, but if you hit any issues let me know. I've also patched 1.0.1 and rebuilt - I am still trying to work out a best-practice for versioning in github, and I think it's clear I still have some way to go there. Until I do, building from HEAD might not be a bad idea.

**Comment by stodge** [comment]
Ah, that's a nice, clean solution. I'll try it out for sure, thanks.

**Comment by stodge** [comment]
Initial testing looks good. I think I can move my project 100% to Zeroconf now. 🙂
